FROM golang:alpine AS backend

COPY ./kernel /kernel

WORKDIR /kernel

RUN go build \
    -ldflags "-X 'github.com/setcy/wiki/kernel/server.Mode=allInOne'" \
    -o /bin/wiki-kernel \
    *.go

FROM node:18 AS frontend

COPY ./app /app

WORKDIR /app

RUN if [ -d "node_modules" ]; then rm -rf node_modules; fi
RUN if [ -d "dist" ]; then rm -rf dist; fi

RUN npm install -g pnpm && pnpm install && pnpm run build

FROM alpine:latest

COPY --from=backend /bin/wiki-kernel /app/wiki-kernel
COPY --from=frontend /app/dist /app/static

WORKDIR /app

CMD ["/app/wiki-kernel"]

EXPOSE 8080